/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appproyectoform;

import static appproyectoform.DBRegistros.productos;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.text.Normalizer;
import java.util.Objects;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CHAPTOPS TACTIC
 */
public class FormProductos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormProductos.class.getName());
    
    
    /**
     * Creates new form FormProductos
     */
    public FormProductos() {
        initComponents();
        //Se centra el formulario
        this.setLocationRelativeTo(null);
        //Se le coloca la fuente a los labels o títulos
        lblTituloForm.setFont(FuentePersonalizada.fuentePersonalizada());
        lblCod.setFont(FuentePersonalizada.fuentePersonalizada());
        lblNombre.setFont(FuentePersonalizada.fuentePersonalizada());
        lblPrecio.setFont(FuentePersonalizada.fuentePersonalizada());
        lblStock.setFont(FuentePersonalizada.fuentePersonalizada());
        lblBuscar.setFont(FuentePersonalizada.fuentePersonalizada());
        //Se le coloca la fuente a los botones
        btnBuscar.setFont(FuentePersonalizada.fuentePersonalizada());
        btnLimpiar.setFont(FuentePersonalizada.fuentePersonalizada());
        btnVenta.setFont(FuentePersonalizada.fuentePersonalizada());
        btnRegistrar.setFont(FuentePersonalizada.fuentePersonalizada());
        btnSalir.setFont(FuentePersonalizada.fuentePersonalizada());
        //se refresca la vista cada vez que se ingresa al form
        refrescarVista();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloForm = new javax.swing.JLabel();
        lblCod = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnVenta = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloForm.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblTituloForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloForm.setText("Inventario de Productos");
        jPanel1.add(lblTituloForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 480, -1));

        lblCod.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCod.setText("Código:");
        jPanel1.add(lblCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 87, 100, -1));

        lblNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNombre.setText("Nombre:");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 125, 100, -1));

        lblPrecio.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblPrecio.setText("Precio:");
        jPanel1.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 169, 80, -1));

        lblStock.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblStock.setText("Stock:");
        jPanel1.add(lblStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 213, 90, -1));

        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 84, 437, -1));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 122, 437, -1));

        txtPrecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 166, 437, -1));

        txtStock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 210, 437, -1));

        btnRegistrar.setBackground(new java.awt.Color(153, 255, 153));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 130, -1));

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 130, -1));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Precio", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 343, 584, 270));

        lblBuscar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblBuscar.setText("Buscar Producto:");
        jPanel1.add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 257, -1, -1));

        txtBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBuscar.addActionListener(this::txtBuscarActionPerformed);
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 254, 380, -1));

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 94, -1));

        btnSalir.setBackground(new java.awt.Color(255, 51, 51));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 662, 140, 30));

        btnVenta.setBackground(new java.awt.Color(51, 204, 255));
        btnVenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVenta.setText("Registrar Venta");
        btnVenta.addActionListener(this::btnVentaActionPerformed);
        jPanel1.add(btnVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 298, -1, -1));

        lblFondo.setBackground(new java.awt.Color(255, 0, 0));
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/asadal_stock_62.jpg"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaActionPerformed
        
        //se crea una instancía del formulario
        FormVentas formVentas = new FormVentas();
        //se hace visible el form
        formVentas.setVisible(true);
        //se cierra la ventana actual 
        this.dispose();
    }//GEN-LAST:event_btnVentaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            String codigo = txtCodigo.getText();
            String nombre = txtNombre.getText();
            double precio = Double.parseDouble(txtPrecio.getText());
            int stock = Integer.parseInt(txtStock.getText());
            
            if (existeCodigo(codigo)) {
                JOptionPane.showMessageDialog(this,"Ya existe un alumno con ese carne, favor validar.");
                return; 
            }
            
            Producto p = new Producto(codigo, nombre, precio, stock);
            DBRegistros.productos.add(p);
            
            refrescarVista();

             
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Ocurrió un error, intente de nuevo.");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String codigo = txtBuscar.getText();
        
        Producto c = buscarProducto(codigo);
        
        if (Objects.isNull(c)){
            JOptionPane.showMessageDialog(this, "No se encontró el codigo.");
        }
        
        
        
        refrescarBusqueda(c);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed
  
    private void refrescarVista(){
        DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel(); //Obtener el modelo de la tabla
        modelo.setRowCount(0); //Vaciar la tabla
        
        for (int i = 0; i < DBRegistros.productos.size(); i++) { /*Recorrer toda la lista para volver a llenar la tabla*/
            Producto p = productos.get(i); /*Extrae el estudiantes en la posición i*/
            
            modelo.addRow(new Object[]{
                p.getCodigo(),/*Nombre*/
                p.getNombre(),/*Carne*/
                p.getPrecio(),/*Nota*/
                p.getStock() 
            });

        }
        
    } 
    
    private boolean existeCodigo(String codigo){
        for (int i = 0; i < DBRegistros.productos.size(); i++) {
            Producto e = DBRegistros.productos.get(i);
            
            if (e.getCodigo().equalsIgnoreCase(codigo)) {
                return true;
            }
        }
        
        return false;
    }
    
    
    private Producto buscarProducto(String codigo){
        //
        for (int i = 0; i < DBRegistros.productos.size(); i++){
            if (DBRegistros.productos.get(i).getCodigo().equalsIgnoreCase(codigo)){ 
                //si encuentra un código igual retorna el objeto
                return DBRegistros.productos.get(i); 
            }
            
        }
        //Si no encuentra nada retorna null
       return null;
    }
    
    private void refrescarBusqueda(Producto busqueda){
        DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();
        modelo.setRowCount(0);
        
        modelo.addRow(new Object[]{
            busqueda.getCodigo(),
            busqueda.getNombre(),
            busqueda.getPrecio(),
            busqueda.getStock()
        });
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormProductos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVenta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCod;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTituloForm;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
