/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appproyectoform;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Objects;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CHAPTOPS TACTIC
 */
public class FormVentas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormVentas.class.getName());

    /**
     * Creates new form FormVentas
     */
    public FormVentas() {
        initComponents();
        //Se centra el form
        this.setLocationRelativeTo(null);
        //Se setea que la tabla no sea editable 
        tbVentas.setEnabled(false);
        
        lblTituloForm.setFont(FuentePersonalizada.fuentePersonalizada());
        lblCodV.setFont(FuentePersonalizada.fuentePersonalizada());
        lblCodP.setFont(FuentePersonalizada.fuentePersonalizada());
        lblCantidad.setFont(FuentePersonalizada.fuentePersonalizada());
        lblTotalVentas.setFont(FuentePersonalizada.fuentePersonalizada());
        btnLimpiar.setFont(FuentePersonalizada.fuentePersonalizada());
        btnRegistrar.setFont(FuentePersonalizada.fuentePersonalizada());
        btnRegresar.setFont(FuentePersonalizada.fuentePersonalizada());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloForm = new javax.swing.JLabel();
        lblCodP = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        txtCodigoProducto = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVentas = new javax.swing.JTable();
        lblTotalVentas = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        txtSalida = new javax.swing.JLabel();
        lblCodV = new javax.swing.JLabel();
        txtCodigoVenta = new javax.swing.JTextField();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloForm.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTituloForm.setText("Registro de Ventas");
        jPanel1.add(lblTituloForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 27, -1, -1));

        lblCodP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCodP.setText("Código de Producto:");
        jPanel1.add(lblCodP, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 107, 200, -1));

        lblCantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCantidad.setText("Cantidad:");
        jPanel1.add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 145, 160, -1));

        txtCodigoProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 104, 400, -1));

        txtCantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 142, 400, -1));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 140, -1));

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 130, -1));

        tbVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo de Venta", "Codigo de Producto", "Nombre", "Cantidad", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbVentas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 239, 596, 270));

        lblTotalVentas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalVentas.setText("Total de ventas: ");
        jPanel1.add(lblTotalVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 515, -1, 42));

        btnRegresar.setBackground(new java.awt.Color(153, 255, 204));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 630, 150, 40));

        txtSalida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 515, 450, 42));

        lblCodV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCodV.setText("Código de Venta:");
        jPanel1.add(lblCodV, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 69, 190, -1));

        txtCodigoVenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCodigoVenta.addActionListener(this::txtCodigoVentaActionPerformed);
        jPanel1.add(txtCodigoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 66, 400, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/asadal_stock_30.jpg"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 690, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:

        //se crea una instancía del formulario
        FormProductos formProductos = new FormProductos();
        //se hace visible el form
        formProductos.setVisible(true);
        //se cierra la ventana actual
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        
        try {
            //se extraen los datos de los campos
            String codigoVenta = txtCodigoVenta.getText();
            String codigoProducto = txtCodigoProducto.getText();
            int cantidad = Integer.parseInt(txtCantidad.getText());
            
            //se valida el campo que no este vacío
            if(codigoProducto.trim().isEmpty() || codigoVenta.trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Llene los campos vacíos");
                return;
            }
            
            //se valida que aun no exista el codigo de venta ingresado
            if(existeCodigoVenta(codigoVenta)){
                JOptionPane.showMessageDialog(this, "Ya existe una venta registrada con ese codigo");
                return;
            }
            
            //se extrae el producto de la lista 
            Producto p = buscar_por_codigo(codigoProducto);
            
            //se valida que se encontro el producto
            if(Objects.isNull(p)){
                JOptionPane.showMessageDialog(this, "No se encontro el producto, valide que el codigo sea valido");
                return;
            }
            
            //se descuenta y valida, del stock del producto
            if(!p.descontar_de_stock(cantidad)){
                JOptionPane.showMessageDialog(this, "No hay stock suficiente para realizar la venta");
                return;
            }
            
            //se registra la venta en la lista
            DBRegistros.ventas.add(new Venta(codigoVenta, p, cantidad));
            
            //se refresca la vista
            refrescarListado();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error valide los campos");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        // se limpian los campos
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtCodigoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoVentaActionPerformed

    //busca y retorna el producto mediante el codigo
    private Producto buscar_por_codigo(String codigo){
        //se recorre la lista de productos y se retorna el 
        //objeto cuando se encuentra
        for (Producto p : DBRegistros.productos) {
            if(p.getCodigo().equalsIgnoreCase(codigo)) return p;
        }
        return null;
    }
    
    private void limpiar(){
        txtCodigoProducto.setText(" ");
        txtCantidad.setText("");
        txtCodigoProducto.setText("");
    }
    
    private void refrescarListado(){
        //se crea una variable para acumular cada total
        double total = 0; 
        //se obtiene el modelo de la tabla
        DefaultTableModel modelo = (DefaultTableModel) tbVentas.getModel();
        modelo.setRowCount(0); //se vacía la tabla
        
        //se recorre la lista de ventas y se va agregando cada objeto a la tabla
        for (Venta v : DBRegistros.ventas) {
            modelo.addRow(new Object[]{
                v.getCodigo(), //codigo de la venta
                v.getProducto().getCodigo(), //codigo de producto
                v.getProducto().getNombre(), //nombre de producto
                v.getCantidad(), //cantidad
                v.total() //total de venta
            });
            //se acumula cada total
            total += v.total();
        }
        
        definirTotalFinal(total);
    }
    
    private void definirTotalFinal(double total){
        //se castea el total
        String t = String.valueOf(total);
        //actualiza el total de txtSalida
        txtSalida.setText(t);
    }
    
    private boolean existeCodigoVenta(String codigo){
        //se recorre la lista de ventas 
        for (Venta v : DBRegistros.ventas) {
            //se verifica si es el codigo
            if(v.getCodigo().equalsIgnoreCase(codigo)) return true;
        }
        return false;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormVentas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCodP;
    private javax.swing.JLabel lblCodV;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblTituloForm;
    private javax.swing.JLabel lblTotalVentas;
    private javax.swing.JTable tbVentas;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigoProducto;
    private javax.swing.JTextField txtCodigoVenta;
    private javax.swing.JLabel txtSalida;
    // End of variables declaration//GEN-END:variables
}
